### ISSUE TITLE
Param objects could have ability to provide containers for multiple objects.

### ISSUE THREAD

**Issue by swistakm** [swistakm/graceful#16]
In some situations when we have `many=True` option on parameter provided it might be useful to provide a custom container type/class or method for grouping multiple instances.

Now every param class has only one method handler for single value param. Thanks to this implementation of parameter is short and consistent regardless of the `many` option setting. If multiple parameters are allowed then we always use list to contain provided parameters. Custom containers would be useful for additional preprocessing of params.

Here is example how this would work on real world example that allows joining multiple occurrences of `solrq.Q` object with specified operator ([solrq](https://github.com/swistakm/solrq) is example external package):

```python
from graceful.params import StringParam

import operator
from functools import reduce

class FilterQueryParam(StringParam):
    """
    Param that represents Solr filter queries logically 
   joined together depending on value of `op` argument
    """
    def __init__(
            self,
            details,
            solr_field,
            op=operator.and_,
            **kwargs
    ):
        if solr_field is None:
            raise ValueError("{} needs a `field` param cannot be None".format(
                self.__class__.__name__)
            )

        self.solr_field = solr_field
        self.op = op

        super(FilterQueryParam, self).__init__(
            details, **kwargs
        )

    def value(self, raw_value):
        return Q({self.solr_field: raw_value})

    def container(self, values):
        return reduce(self.op, values) if len(values) > 1 else values[0]
```

With such API whenever `many` is set to true then `.container()` will be fed with list of values got from multiple calls to `.value()` method handler. Additionally there can be an additional `container_class`  keyword argument stored as Param attribute on initialisation (default `container=list`) that will be used by default implementation of container method:

```python

class BaseParam(object):
    ...

    def container(self, values):
       return self.container_class(values)
```   

In this way this feature can be used even on existing basic Param classes without the need of creating custom param definitions.

**Comment by swistakm** [comment]
@dreamwalker, @mihau: I will glad to hear your opinion on this feature draft because I know that you are the users of graceful.

**Comment by swistakm** [comment]
I found even more simpler solution. Knowing that functions in Python are descriptors we can allow to specify containers both as class (type) objects and custom methods using only one class attribute: `container`. The `BaseParam` implementation for that feature would be as follows:

```python
class BaseParam():
    container = list
    ...
```

If someone wants to have more complex behaviour he can still implement it as a method. That way we get rid of additional class attribute and extra method call for default behaviour.

I was thinking also about adding additional `container` keyword argument to `BaseParam.__init__` that would allow us to override default container type without the need of subclassing.

Anyone want's to comment on that? @mihau? @tomislater?

**Comment by tomislater** [comment]
Hmm, looks right for me. If someone wants to get more values (not list), he/she can create a function for this (container).

I have another idea. What if we would have `value` and `values` methods?
Then, if someone passes param `many=True`, he has to implement `values` method.

For example:

```python
class BaseParam:
    def value(self, raw_value):
        raise NotImplementedError

    def values(self, raw_values):
        # raw_values is a list
        raise NotImplementedError

class MyParam(BaseParam):
    def value(self, raw_value):
        return my_magic_function(raw_value)

    def values(self, raw_values):
        return my_magic_function_for_list(raw_values)
```

I understand that with this approach, we will have to change the logic in `BaseResource.require_params` method concerning getting params.

**Comment by swistakm** [comment]
It seems interesting but I don't know if I get the whole point of this idea. Does `values` is supposed to:
0. get the list of deserialised values (results of calling `value()` for each one of them)?
0. get list of raw strings from query string params (via request `req.get_param_as_list()`) 

If this is (1.) then I think that this is almost the same solution as the proposed with `container` but named differently.

If it is (2.) then I think that right now there is very limited gain from such splitting of implementation. I worry that this would make easier for users to take bad design decisions about how their params work. Generally param instances are used to describe parsing/deserialization of single query string parameter and such behaviour should not change with custom `many` setting.

Anyway, I do not say definitive no to any of these options. I think we should keep such idea in mind and revisit it later in future if someone finds really practical use case for that.

**Comment by tomislater** [comment]
Yeah, I have meant the first point. I have thought about the second approach (raw values), but it could be hard to understand.
