### ISSUE TITLE
Consider getting rid of default param value in "raw" or at least deserialising it only once

### ISSUE THREAD

**Issue by swistakm** [swistakm/graceful#28]
As noted in #27 PR default values are deserialised and validated every time they are retrieved and this could be obviously improved. Consider getting rid of that limitation or making default value deserialised only once on init.

**Comment by swistakm** [comment]
I remove it from 0.3.0 milestone because:
* in case of changing the default value from "raw" to "native" we will  break backwards compatibility so it should land in at least 1.0.0
* in case of changing param handling to deserialise default value only once it will be simple enhancement that can be done even in patch release

**Comment by tomislater** [comment]
> in case of changing param handling to deserialise default value only once it will be simple enhancement that can be done even in patch release

Ok, I have tried to do this, and it makes no sense. The code is not more readable after this change, and the logic is complicated.

**Comment by swistakm** [comment]
Ok, let's close it then.
