### ISSUE TITLE
Support for fields that can be null/blank

### ISSUE THREAD

**Issue by swistakm** [swistakm/graceful#3]
Decide which approach is better:
- additional classes for fields that support null/blank
- additional ~parameter(s)~ arguments(s) in `BaseField` class that support null/blank
- additional field class wrapper that adds such possibility (like: `field = AllowNull(StringField("foo'))`

**Comment by tomislater** [comment]
The second approach looks good to me. Could you explain the first point? I think, I don't get what do you exactly mean. Thanks!
